### ISSUE TITLE
Add Parameter type in csharp model pack editor for sourceModel.

### ISSUE THREAD

**Issue by Hug0Vincent** [github/vscode-codeql#4054]
**Is your feature request related to a problem? Please describe.**
The CodeQL model editor for csharp does not allow to add a `Parameter` for a `sourceModel`:

![Image](https://github.com/user-attachments/assets/74bf1264-c0bb-4fcd-880e-f234641ab3fb)

**Describe the solution you'd like**
It would be nice to add the `Parameter` option to generate things like this:

```
extensions:
  - addsTo:
      pack: codeql/csharp-all
      extensible: sourceModel
    data:
      - ["Abp.Web.Models", "AjaxResponseBase", False, "set_TargetUrl", "(System.String)", "", "Parameter[0]", "remote", "manual"]
```

**Describe alternatives you've considered**
For now I need to open the generated model pack and replace manually `Argument[0]` by `Parameter[0]`.
